iota:
  nodeUri: https://nodes.devnet.iota.org:443
  nodeZmqUri: tcp://zmq.devnet.iota.org:5556
  seed: OVMJZTDTEAGWMZMVF9QVJFU9XTVCGVQJNHDMODERIHSARNQKACZNJNUN9RWHAINOQYYAVZ9RWSMQRJGHA
airconditioner:
  enabled: true
  baseUrl: http://192.168.1.21
  tickDuration: 60000
  tickCost: 500
server:
  port: 80
  user: admin
  password: pass
