'use strict';

const EVENT_STATE_CHANGED = 'STATE_CHANGED';
const EVENT_BTN_ONOFF_PRESSED = 'BTN_ONOFF_PRESSED';
const EVENT_PROCESSING = 'PROCESSING';
const EVENT_TICK = 'TICK';
const EVENT_PAID = 'PAID';
const EVENT_UNPAID = 'UNPAID';
const STATUS_ON = 'ON';
const STATUS_OFF = 'OFF';

// Interval to poll for the room temperature, in milliseconds
const THERMOMETER_MEASURE_INTERVAL = 60000;

module.exports = {
    EVENT_STATE_CHANGED,
    EVENT_BTN_ONOFF_PRESSED,
    EVENT_PROCESSING,
    EVENT_TICK,
    EVENT_PAID,
    EVENT_UNPAID,
    STATUS_ON,
    STATUS_OFF,
    THERMOMETER_MEASURE_INTERVAL,
};
